export enum ErrorMessages {
  Conflict = 'The resource already exists',
  NotFound = 'The resource does not exist',
  Unauthorized = 'Unauthorized',
  Forbidden = 'Forbidden',
  InternalServerError = 'Internal Server Error',
  BadRequest = 'Bad Request',
  UnprocessableEntity = 'Unprocessable Entity',
  ValidationError = 'Validation Error',
  InvalidCredentials = 'Invalid credentials',
  InvalidRefreshToken = 'Invalid refresh token',
  InvalidAccessToken = 'Invalid access token',
  InvalidOrMissingAccessToken = 'Access token is missing or invalid',
  UserNotFound = 'User not found',
  ResourceNotFound = 'Resource not found',
  UserInactive = 'User is not active',
}
